### ISSUE TITLE
"chare init" prints usage message instead of creating project from template

### ISSUE THREAD

**Issue by dpurge** [dwqs/chare#1]
I've tried to use chare to create a project from dwqs/vue-typescript template.
It has printed usage information on the screen, and did not create the project.

Here is copy from my console:

```
> chare init dwqs/vue-typescript vue-learn



  Usage: chare-init <template-name> [project-name]


  Options:

    -c, --clone   use git clone
    -o, --origin  set git remote origin
    -h, --help    output usage information
  Examples:

    # create a new project with an template from github.
    $ chare init dwqs/vue-startup my-project
    $ chare init dwqs/vue-startup my-project -o git@github.com:xx/xxxx.git
```

This is from the current code, installed with `npm link` 

Using template from local directory does work:

```
$ chare init C:/src/pub/dwqs/vue-typescript  vue-learn


Template is from C:/src/pub/dwqs/vue-typescript

** generating project vue-learn...

? Project name: vue-learn
? Author: <!-- edited -->
? Project version: 0.0.1
? Project description: A new Vue.js + TypeScript project
? state manage for your app: mobx
? client port: 3000
? Need image minifying in production?: Yes

√ vue-learn generated  success


   To get started:

     cd vue-learn
     npm install
     npm run dll
     npm run dev

   Documentation can be found at https://github.com/dwqs/vue-typescript
```

**Comment by dwqs** [comment]
Maybe there is some wrong for this template, let's me see. You can try others template, [vue-startup](https://github.com/dwqs/vue-startup), [react-startup](https://github.com/dwqs/react-startup), etc.

**Comment by dwqs** [comment]
Maybe my owner repos is too many(31), so the template `dwqs/vue-typescript` doesn't exist the response from the [Github API](https://developer.github.com/v3/repos/#list-user-repositories), the code is [here](https://github.com/dwqs/chare/blob/dev/src/check-repos.js#L22-L41). Because it returns the first page of data default(the page size is 30). But I have 31 repos and the `vue-typescript` is the 31st.  So you got nothing when use it to generate your project.  I have fix it and just upgrade chare-cli.
